from __future__ import annotations

from pathlib import Path

import pyray as pr

# Version checked: raylib 5.x/pyray API parity (reviewed 2026-02-28).

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 450
PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 = getattr(pr, "PIXELFORMAT_UNCOMPRESSED_R8G8B8A8", 7)


def main() -> None:
    """Run raw image loading and generated-checker texture demo."""
    pr.init_window(SCREEN_WIDTH, SCREEN_HEIGHT, "raylib [textures] example - raw data")

    resources = Path(__file__).resolve().parent / "resources"
    fudesumi_raw = pr.load_image_raw(
        str(resources / "fudesumi.raw"),
        384,
        512,
        PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
        0,
    )
    fudesumi = pr.load_texture_from_image(fudesumi_raw)
    pr.unload_image(fudesumi_raw)

    checked_image = pr.gen_image_checked(960, 480, 32, 32, pr.ORANGE, pr.GOLD)
    checked = pr.load_texture_from_image(checked_image)
    pr.unload_image(checked_image)

    pr.set_target_fps(60)

    while not pr.window_should_close():
        pr.begin_drawing()
        pr.clear_background(pr.RAYWHITE)

        pr.draw_texture(
            checked,
            SCREEN_WIDTH // 2 - checked.width // 2,
            SCREEN_HEIGHT // 2 - checked.height // 2,
            pr.fade(pr.WHITE, 0.5),
        )
        pr.draw_texture(fudesumi, 430, -30, pr.WHITE)

        pr.draw_text("CHECKED TEXTURE ", 84, 85, 30, pr.BROWN)
        pr.draw_text("GENERATED by CODE", 72, 148, 30, pr.BROWN)
        pr.draw_text("and RAW IMAGE LOADING", 46, 210, 30, pr.BROWN)
        pr.draw_text(
            "(c) Fudesumi sprite by Eiden Marsal",
            310,
            SCREEN_HEIGHT - 20,
            10,
            pr.BROWN,
        )
        pr.end_drawing()

    pr.unload_texture(fudesumi)
    pr.unload_texture(checked)
    pr.close_window()


if __name__ == "__main__":
    main()
